
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /blog/about.html
  Archives: /blog/archives

social:
  github: https://github.com/YuyingWu
  weibo: http://www.weibo.com/wuyuying1128
  douban: http://www.douban.com/people/wuyuying1128

license: 京ICP备16019960号

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /blog/css/paper.lib.css
- /blog/css/basscss.lib.css
- /blog/css/index.css

# scripts loaded in the end of the body
scripts:
- /blog/js/lazyload.js
- /blog/js/index.js
